# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  head_pitch:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  head_yaw:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  left_ankle_pitch:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  left_ankle_roll:
    has_velocity_limits: true
    max_velocity: 6.597344565
    has_acceleration_limits: false
    max_acceleration: 0
  left_elbow:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  left_hip_pitch:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  left_hip_roll:
    has_velocity_limits: true
    max_velocity: 6.597344565
    has_acceleration_limits: false
    max_acceleration: 0
  left_hip_yaw:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  left_knee:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  left_shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 6.597344565
    has_acceleration_limits: false
    max_acceleration: 0
  left_shoulder_roll:
    has_velocity_limits: true
    max_velocity: 5.648668
    has_acceleration_limits: false
    max_acceleration: 0
  right_ankle_pitch:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  right_ankle_roll:
    has_velocity_limits: true
    max_velocity: 6.597344565
    has_acceleration_limits: false
    max_acceleration: 0
  right_elbow:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  right_hip_pitch:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  right_hip_roll:
    has_velocity_limits: true
    max_velocity: 6.597344565
    has_acceleration_limits: false
    max_acceleration: 0
  right_hip_yaw:
    has_velocity_limits: true
    max_velocity: 5.6548668
    has_acceleration_limits: false
    max_acceleration: 0
  right_knee:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  right_shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 6.597344565
    has_acceleration_limits: false
    max_acceleration: 0
  right_shoulder_roll:
    has_velocity_limits: true
    max_velocity: 5.648668
    has_acceleration_limits: false
    max_acceleration: 0