# dummy_handler
dummy_handler_input: 0

# ros_handler
ROS_handler_img_msg_topic: 'image_raw'
ROS_handler_img_queue_size: 1

ROS_handler_action_server_name: 'VisualCompassSetGroundTruth'

# compass
# Choose from 'binary' or 'multiple'
compass_type: 'multiple'

# Choose from: 'akaze', 'orb', 'sift'
compass_matcher: 'sift'

# binary

# multiple
compass_multiple_sample_count: 8

# orb
compass_orb_max_feature_count: 1000
compass_orb_match_distance_scalar: 0.7
# akaze
compass_akaze_match_distance_scalar: 0.7
# sift
compass_sift_devicetype: 'cpu'

# evaluator data path
evaluation_data: '../evaluation_data/FieldData/Field_1/'
