########
# MISC #
########

# set the color of your team
# 2: red
# 3: blue
# other values are invalid
team_color: 2

# the initial pose of the robot
initial_robot_x: 0
initial_robot_y: 0

# the field size in meters
field_height: 9
field_width: 6

#############
# ROS-Stuff #
#############

ball_topic: '/pixels_relative'

obstacles_topic: '/obstacles_relative'

team_data_topic: '/team_data'

local_model_topic: '/local_world_model'

global_model_topic: '/global_world_model'

local_particles_topic: '/local_particles'

global_particles_topic: '/global_particles'

reset_filters_service_name: 'WorldModel/reset_filters'

local_publishing_frame: '/base_footprint'

global_publishing_frame: '/map'

publishing_frequency: 10

#################
# Visualization #
#################

debug_visualization: true
local_ball_gmm_visualization: false
local_mate_gmm_visualization: false
local_opponent_gmm_visualization: false
local_obstacle_gmm_visualization: false

ball_marker_color: 2  # yellow
mate_marker_color: 5  # green
opponent_marker_color: 4  # red
obstacle_marker_color: 3 # blue

####################
# Particle Filters #
####################

# Local Filters
# -------------

local_ball_particle_number: 2000
local_ball_diffusion_x_std_dev: 1
local_ball_diffusion_y_std_dev: 1
local_ball_diffusion_multiplicator: 0.1
local_ball_min_weight: 0.001
local_ball_explorer_rate: .2
local_ball_max_distance: 18
local_ball_gmm_components: 1
local_ball_gmm_delta: 0.1
local_ball_gmm_iterations: 10

local_mate_particle_number: 2000
local_mate_diffusion_x_std_dev: 1
local_mate_diffusion_y_std_dev: 1
local_mate_diffusion_multiplicator: 0.1
local_mate_min_weight: 0.001
local_mate_explorer_rate: .2
local_mate_max_distance: 18
local_mate_gmm_min_components: 1
local_mate_gmm_max_components: 5
local_mate_gmm_component_count_max_delta: 1
local_mate_gmm_component_delta: 1000
local_mate_gmm_iteration_delta: 0.01
local_mate_gmm_iterations: 10

local_opponent_particle_number: 2000
local_opponent_diffusion_x_std_dev: 1
local_opponent_diffusion_y_std_dev: 1
local_opponent_diffusion_multiplicator: 0.1
local_opponent_min_weight: 0.001
local_opponent_explorer_rate: .05
local_opponent_max_distance: 18
local_opponent_gmm_min_components: 1
local_opponent_gmm_max_components: 5
local_opponent_gmm_component_count_max_delta: 1
local_opponent_gmm_component_delta: 1000
local_opponent_gmm_iteration_delta: 0.01
local_opponent_gmm_iterations: 10

local_obstacle_particle_number: 2000
local_obstacle_min_width: 0.1
local_obstacle_max_width: 2
local_obstacle_diffusion_x_std_dev: 1
local_obstacle_diffusion_y_std_dev: 1
local_obstacle_diffusion_multiplicator: 0.1
local_obstacle_min_weight: 0.001
local_obstacle_explorer_rate: .05
local_obstacle_max_distance: 18
local_obstacle_gmm_min_components: 1
local_obstacle_gmm_max_components: 5
local_obstacle_gmm_component_count_max_delta: 1
local_obstacle_gmm_component_delta: 1000
local_obstacle_gmm_iteration_delta: 0.01
local_obstacle_gmm_iterations: 10


# Global Filters
# -------------

global_ball_particle_number: 2000
global_ball_diffusion_x_std_dev: 1
global_ball_diffusion_y_std_dev: 1
global_ball_diffusion_multiplicator: 0.1
global_ball_min_weight: 0.001
global_ball_explorer_rate: .2
global_ball_max_distance: 18

global_mate_particle_number: 2000
global_mate_diffusion_x_std_dev: 1
global_mate_diffusion_y_std_dev: 1
global_mate_diffusion_multiplicator: 0.1
global_mate_min_weight: 0.001
global_mate_explorer_rate: .2
global_mate_max_distance: 18

global_opponent_particle_number: 100
global_opponent_diffusion_x_std_dev: 1
global_opponent_diffusion_y_std_dev: 1
global_opponent_diffusion_multiplicator: 0.1
global_opponent_min_weight: 0.001
global_opponent_explorer_rate: .05
global_opponent_max_distance: 18

global_obstacle_particle_number: 2000
global_obstacle_diffusion_x_std_dev: 1
global_obstacle_diffusion_y_std_dev: 1
global_obstacle_diffusion_multiplicator: 0.1
global_obstacle_min_weight: 0.001
global_obstacle_explorer_rate: .05
global_obstacle_max_distance: 18

