########
# MISC #
########

# set the color of your team
# 2: red
# 3: blue
# other values are invalid
team_color: 2

# the initial pose of the robot
initial_robot_x: 0
initial_robot_y: 0

# the field size in meters
field_height: 9
field_width: 6

#############
# ROS-Stuff #
#############

obstacles_topic: '/obstacles'

local_model_topic: '/local_world_model'

global_model_topic: '/global_world_model'

publishing_frequency: 10


####################
# Particle Filters #
####################

# Local Filters
# -------------

local_mate_particle_number: 100

local_opponent_particle_number: 100

local_obstacle_particle_number: 100
local_obstacle_min_width: 0.1
local_obstacle_max_width: 2

