########
# MISC #
########

# set the color of your team
# 2: red
# 3: blue
# other values are invalid
team_color: 2

# the initial pose of the robot
initial_robot_x: 0
initial_robot_y: 0

# the field size in meters
field_height: 9
field_width: 6

#############
# ROS-Stuff #
#############

obstacles_topic: '/obstacles'

local_model_topic: '/local_world_model'

global_model_topic: '/global_world_model'

local_particles_topic: '/local_particles'

reset_filters_service_name: 'WorldModel/reset_filters'

publishing_frequency: 10

#################
# Visualization #
#################

debug_visualization: true

mate_marker_color: 5  # green
opponent_marker_color: 4  # red
obstacle_marker_color: 3 # blue

####################
# Particle Filters #
####################

# Local Filters
# -------------

local_mate_particle_number: 100
local_mate_diffusion_x_std_dev: 1
local_mate_diffusion_y_std_dev: 1
local_mate_diffusion_multiplicator: 0.1
local_mate_min_weight: 0.001
local_mate_explorer_rate: .05
local_mate_max_distance: 18

local_opponent_particle_number: 100
local_opponent_diffusion_x_std_dev: 1
local_opponent_diffusion_y_std_dev: 1
local_opponent_diffusion_multiplicator: 0.1
local_opponent_min_weight: 0.001
local_opponent_explorer_rate: .05
local_opponent_max_distance: 18

local_obstacle_particle_number: 2000
local_obstacle_min_width: 0.1
local_obstacle_max_width: 2
local_obstacle_diffusion_x_std_dev: 1
local_obstacle_diffusion_y_std_dev: 1
local_obstacle_diffusion_multiplicator: 0.1
local_obstacle_min_weight: 0.001
local_obstacle_explorer_rate: .05
local_obstacle_max_distance: 18

