team_communication:

  # The port to be used
  port: 12321

  team: 7

  player: 99

  # Rate of published messages in Hz
  rate: 1

  # avarange walking speed in mm / s !!!
  avg_walking_speed: 10

  # in mm
  max_kicking_distance: 1000